// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsCEZFDTnzDwfOhGg-erm1aCJdzglohng',
    appId: '1:53385504020:web:20b4a14ae1654a6da94e01',
    messagingSenderId: '53385504020',
    projectId: 'fir-app3-2a24e',
    authDomain: 'fir-app3-2a24e.firebaseapp.com',
    storageBucket: 'fir-app3-2a24e.appspot.com',
    measurementId: 'G-R927LFZDDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGG3pcQdbfF5zj_TZsiBjfzRzwqeMCIXk',
    appId: '1:53385504020:android:de01663fa7be5d49a94e01',
    messagingSenderId: '53385504020',
    projectId: 'fir-app3-2a24e',
    storageBucket: 'fir-app3-2a24e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTrU0OCtdI7cHoH9czSM8EkkpJOz8CvA',
    appId: '1:53385504020:ios:432cffe6a475e736a94e01',
    messagingSenderId: '53385504020',
    projectId: 'fir-app3-2a24e',
    storageBucket: 'fir-app3-2a24e.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTrU0OCtdI7cHoH9czSM8EkkpJOz8CvA',
    appId: '1:53385504020:ios:432cffe6a475e736a94e01',
    messagingSenderId: '53385504020',
    projectId: 'fir-app3-2a24e',
    storageBucket: 'fir-app3-2a24e.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsCEZFDTnzDwfOhGg-erm1aCJdzglohng',
    appId: '1:53385504020:web:c49f0468e55b5075a94e01',
    messagingSenderId: '53385504020',
    projectId: 'fir-app3-2a24e',
    authDomain: 'fir-app3-2a24e.firebaseapp.com',
    storageBucket: 'fir-app3-2a24e.appspot.com',
    measurementId: 'G-BY9D20QS2M',
  );
}
